import type { ModelDef } from '@koryphaios/shared';

// Antigravity CLI harness models. These run through the `agy` CLI (Google subscription),
// not the Gemini REST API. The apiModelId is the exact string passed to `agy --model`.
// Full list sourced from `agy models`; dynamic refresh supplements this at runtime.
export const AntigravityModels: ModelDef[] = [
  {
    id: 'antigravity-gemini-flash-low',
    name: 'Gemini 3.5 Flash (Low)',
    provider: 'antigravity',
    apiModelId: 'Gemini 3.5 Flash (Low)',
    contextWindow: 1_048_576,
    maxOutputTokens: 65_536,
    canReason: false,
    supportsAttachments: false,
    supportsStreaming: true,
    reasoningLevels: [],
    tier: 'fast',
  },
  {
    id: 'antigravity-gemini-flash',
    name: 'Gemini 3.5 Flash (Medium)',
    provider: 'antigravity',
    apiModelId: 'Gemini 3.5 Flash (Medium)',
    contextWindow: 1_048_576,
    maxOutputTokens: 65_536,
    canReason: false,
    supportsAttachments: false,
    supportsStreaming: true,
    reasoningLevels: [],
    tier: 'fast',
  },
  {
    id: 'antigravity-gemini-flash-high',
    name: 'Gemini 3.5 Flash (High)',
    provider: 'antigravity',
    apiModelId: 'Gemini 3.5 Flash (High)',
    contextWindow: 1_048_576,
    maxOutputTokens: 65_536,
    // The agy CLI exposes no separate reasoning/thinking flag. The suffix is
    // part of this model's identity and must only change through model selection.
    canReason: false,
    supportsAttachments: false,
    supportsStreaming: true,
    reasoningLevels: [],
    tier: 'reasoning',
  },
  {
    id: 'antigravity-gemini-pro-low',
    name: 'Gemini 3.1 Pro (Low)',
    provider: 'antigravity',
    apiModelId: 'Gemini 3.1 Pro (Low)',
    contextWindow: 2_097_152,
    maxOutputTokens: 65_536,
    canReason: false,
    supportsAttachments: false,
    supportsStreaming: true,
    reasoningLevels: [],
    tier: 'flagship',
  },
  {
    id: 'antigravity-gemini-pro',
    name: 'Gemini 3.1 Pro (High)',
    provider: 'antigravity',
    apiModelId: 'Gemini 3.1 Pro (High)',
    contextWindow: 2_097_152,
    maxOutputTokens: 65_536,
    canReason: true,
    supportsAttachments: false,
    supportsStreaming: true,
    reasoningLevels: [],
    tier: 'reasoning',
  },
  {
    id: 'antigravity-claude-sonnet-thinking',
    name: 'Claude Sonnet 4.6 (Thinking)',
    provider: 'antigravity',
    apiModelId: 'Claude Sonnet 4.6 (Thinking)',
    contextWindow: 200_000,
    maxOutputTokens: 16_000,
    canReason: true,
    supportsAttachments: false,
    supportsStreaming: true,
    // No sibling effort variants — empty list suppresses the UI's placebo picker.
    reasoningLevels: [],
    tier: 'reasoning',
  },
  {
    id: 'antigravity-claude-opus-thinking',
    name: 'Claude Opus 4.6 (Thinking)',
    provider: 'antigravity',
    apiModelId: 'Claude Opus 4.6 (Thinking)',
    contextWindow: 200_000,
    maxOutputTokens: 16_000,
    canReason: true,
    supportsAttachments: false,
    supportsStreaming: true,
    // No sibling effort variants — empty list suppresses the UI's placebo picker.
    reasoningLevels: [],
    tier: 'flagship',
  },
  {
    id: 'antigravity-gpt-oss-120b',
    name: 'GPT-OSS 120B (Medium)',
    provider: 'antigravity',
    apiModelId: 'GPT-OSS 120B (Medium)',
    contextWindow: 128_000,
    maxOutputTokens: 16_384,
    canReason: false,
    supportsAttachments: false,
    supportsStreaming: true,
    // No sibling effort variants — empty list suppresses the UI's placebo picker.
    reasoningLevels: [],
    tier: 'fast',
  },
];
