import type { ModelDef } from '@koryphaios/shared';

export const AzureModels: ModelDef[] = [
  {
    id: 'azure.gpt-4.1',
    name: 'Azure OpenAI – GPT 4.1',
    provider: 'azure',
    apiModelId: 'gpt-4.1',
    contextWindow: 1_047_576,
    maxOutputTokens: 20_000,
    costPerMInputTokens: 2.0,
    costPerMOutputTokens: 8.0,
    costPerMInputCached: 0.5,
    costPerMOutputCached: 0.0,
    canReason: false,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: 'flagship',
  },
  {
    id: 'azure.gpt-4.1-mini',
    name: 'Azure OpenAI – GPT 4.1 mini',
    provider: 'azure',
    apiModelId: 'gpt-4.1-mini',
    contextWindow: 200_000,
    maxOutputTokens: 20_000,
    costPerMInputTokens: 0.4,
    costPerMOutputTokens: 1.6,
    costPerMInputCached: 0.1,
    costPerMOutputCached: 0.0,
    canReason: false,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: 'fast',
  },
  {
    id: 'azure.gpt-4.1-nano',
    name: 'Azure OpenAI – GPT 4.1 nano',
    provider: 'azure',
    apiModelId: 'gpt-4.1-nano',
    contextWindow: 1_047_576,
    maxOutputTokens: 20_000,
    costPerMInputTokens: 0.1,
    costPerMOutputTokens: 0.4,
    costPerMInputCached: 0.025,
    costPerMOutputCached: 0.0,
    canReason: false,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: 'cheap',
  },
  {
    id: 'azure.gpt-4.5-preview',
    name: 'Azure OpenAI – GPT 4.5 preview',
    provider: 'azure',
    apiModelId: 'gpt-4.5-preview',
    contextWindow: 128_000,
    maxOutputTokens: 15_000,
    costPerMInputTokens: 75.0,
    costPerMOutputTokens: 150.0,
    costPerMInputCached: 37.5,
    costPerMOutputCached: 0.0,
    canReason: false,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: 'flagship',
  },
  // GPT-4o models deprecated: API retirement Feb 16, 2026
  // Replaced with GPT-5.1/5.2 family below
  {
    id: 'azure.gpt-5.1',
    name: 'Azure OpenAI – GPT 5.1',
    provider: 'azure',
    apiModelId: 'gpt-5.1',
    contextWindow: 128_000,
    maxOutputTokens: 16_384,
    costPerMInputTokens: 1.5,
    costPerMOutputTokens: 12.0,
    canReason: true,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: 'flagship',
  },
  {
    id: 'azure.gpt-5.1-mini',
    name: 'Azure OpenAI – GPT 5.1 mini',
    provider: 'azure',
    apiModelId: 'gpt-5.1-mini',
    contextWindow: 128_000,
    maxOutputTokens: 16_384,
    costPerMInputTokens: 0.15,
    costPerMOutputTokens: 0.6,
    canReason: false,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: 'fast',
  },
  {
    id: 'azure.gpt-5.2',
    name: 'Azure OpenAI – GPT 5.2',
    provider: 'azure',
    apiModelId: 'gpt-5.2',
    contextWindow: 400_000,
    maxOutputTokens: 128_000,
    costPerMInputTokens: 1.25,
    costPerMOutputTokens: 10.0,
    canReason: true,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: 'flagship',
  },
  {
    id: 'azure.gpt-5.2-instant',
    name: 'Azure OpenAI – GPT 5.2 Instant',
    provider: 'azure',
    apiModelId: 'gpt-5.2-instant',
    contextWindow: 400_000,
    maxOutputTokens: 64_000,
    costPerMInputTokens: 0.5,
    costPerMOutputTokens: 2.5,
    canReason: false,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: 'fast',
  },
  {
    id: 'azure.o1',
    name: 'Azure OpenAI – O1',
    provider: 'azure',
    apiModelId: 'o1',
    contextWindow: 200_000,
    maxOutputTokens: 50_000,
    costPerMInputTokens: 15.0,
    costPerMOutputTokens: 60.0,
    costPerMInputCached: 7.5,
    costPerMOutputCached: 0.0,
    canReason: true,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: 'reasoning',
  },
  {
    id: 'azure.o1-mini',
    name: 'Azure OpenAI – O1 mini',
    provider: 'azure',
    apiModelId: 'o1-mini',
    contextWindow: 128_000,
    maxOutputTokens: 50_000,
    costPerMInputTokens: 1.1,
    costPerMOutputTokens: 4.4,
    costPerMInputCached: 0.55,
    costPerMOutputCached: 0.0,
    canReason: true,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: 'reasoning',
  },
  {
    id: 'azure.o3',
    name: 'Azure OpenAI – O3',
    provider: 'azure',
    apiModelId: 'o3',
    contextWindow: 200_000,
    maxOutputTokens: 50_000,
    costPerMInputTokens: 10.0,
    costPerMOutputTokens: 40.0,
    costPerMInputCached: 2.5,
    costPerMOutputCached: 0.0,
    canReason: true,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: 'reasoning',
  },
  {
    id: 'azure.o3-mini',
    name: 'Azure OpenAI – O3 mini',
    provider: 'azure',
    apiModelId: 'o3-mini',
    contextWindow: 200_000,
    maxOutputTokens: 50_000,
    costPerMInputTokens: 1.1,
    costPerMOutputTokens: 4.4,
    costPerMInputCached: 0.55,
    costPerMOutputCached: 0.0,
    canReason: true,
    supportsAttachments: false,
    supportsStreaming: true,
    tier: 'reasoning',
  },
  {
    id: 'azure.o4-mini',
    name: 'Azure OpenAI – O4 mini',
    provider: 'azure',
    apiModelId: 'o4-mini',
    contextWindow: 128_000,
    maxOutputTokens: 50_000,
    costPerMInputTokens: 1.1,
    costPerMOutputTokens: 4.4,
    costPerMInputCached: 0.275,
    costPerMOutputCached: 0.0,
    canReason: true,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: 'reasoning',
  },
];
