import type { ModelDef } from '@koryphaios/shared';

export const GoogleModels: ModelDef[] = [
  // Current Models (February 2026)
  {
    id: 'gemini-3-deep-think',
    name: 'Gemini 3 Deep Think',
    provider: 'google',
    apiModelId: 'gemini-3-deep-think-20260212',
    contextWindow: 2_000_000,
    maxOutputTokens: 128_000,
    costPerMInputTokens: 2.0,
    costPerMOutputTokens: 20.0,
    canReason: true,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: 'reasoning',
  },
  {
    id: 'gemini-3-pro',
    name: 'Gemini 3 Pro',
    provider: 'google',
    apiModelId: 'gemini-3-pro-001',
    contextWindow: 1_000_000,
    maxOutputTokens: 128_000,
    costPerMInputTokens: 1.25,
    costPerMOutputTokens: 10.0,
    canReason: true,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: 'flagship',
  },
  {
    id: 'gemini-3.1-pro',
    name: 'Gemini 3.1 Pro',
    provider: 'google',
    apiModelId: 'gemini-3.1-pro',
    contextWindow: 1_000_000,
    maxOutputTokens: 128_000,
    costPerMInputTokens: 1.5,
    costPerMOutputTokens: 12.0,
    canReason: true,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: 'flagship',
  },
  {
    id: 'gemini-3-flash',
    name: 'Gemini 3 Flash',
    provider: 'google',
    apiModelId: 'gemini-3-flash-001',
    contextWindow: 1_000_000,
    maxOutputTokens: 64_000,
    costPerMInputTokens: 0.1,
    costPerMOutputTokens: 0.4,
    canReason: true,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: 'fast',
  },
  {
    id: 'gemini-2.5-pro',
    name: 'Gemini 2.5 Pro',
    provider: 'google',
    apiModelId: 'gemini-2.5-pro',
    contextWindow: 1_000_000,
    maxOutputTokens: 32_768,
    costPerMInputTokens: 3.5,
    costPerMOutputTokens: 10.5,
    canReason: true,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: 'flagship',
  },
  {
    id: 'gemini-2.5-flash',
    name: 'Gemini 2.5 Flash',
    provider: 'google',
    apiModelId: 'gemini-2.5-flash',
    contextWindow: 1_000_000,
    maxOutputTokens: 8_192,
    costPerMInputTokens: 0.075,
    costPerMOutputTokens: 0.3,
    canReason: false,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: 'fast',
  },
  {
    id: 'gemini-2.5-flash-lite',
    name: 'Gemini 2.5 Flash-Lite',
    provider: 'google',
    apiModelId: 'gemini-2.5-flash-lite',
    contextWindow: 1_000_000,
    maxOutputTokens: 4_096,
    costPerMInputTokens: 0.01,
    costPerMOutputTokens: 0.01,
    canReason: false,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: 'cheap',
  },

  // Legacy Models
  {
    id: 'gemini-2.0-pro-exp',
    name: 'Gemini 2.0 Pro Experimental (Legacy)',
    provider: 'google',
    apiModelId: 'gemini-2.0-pro-exp-02-05',
    contextWindow: 1_000_000,
    maxOutputTokens: 64_000,
    tier: 'flagship',
  },
  {
    id: 'gemini-2.0-flash-exp',
    name: 'Gemini 2.0 Flash Experimental (Legacy)',
    provider: 'google',
    apiModelId: 'gemini-2.0-flash-exp',
    contextWindow: 1_000_000,
    maxOutputTokens: 64_000,
    tier: 'fast',
  },
];
