import type { ModelDef } from '@koryphaios/shared';

/**
 * OpenCode Go — low-cost subscription for popular open coding models.
 * Subscribed at opencode.ai/auth (same API key as OpenCode Zen).
 * Base URL: https://opencode.ai/zen/go/v1
 *
 * Go is dual-protocol: most models use the OpenAI-compatible /v1/chat/completions
 * endpoint, while a subset (MiniMax and Qwen3.x) use the Anthropic-compatible
 * /v1/messages endpoint. The OpenCodeGoProvider dispatches per-model.
 *
 * Model list and pricing verified from https://opencode.ai/docs/go/ (June 2026).
 */
export const OpenCodeGoModels: ModelDef[] = [
  // ── OpenAI-compatible models (/v1/chat/completions) ───────────────────────
  {
    id: 'opencodego.glm-5.2',
    name: 'GLM-5.2 (Go)',
    provider: 'opencodego',
    apiModelId: 'glm-5.2',
    contextWindow: 200_000,
    maxOutputTokens: 32_000,
    costPerMInputTokens: 1.4,
    costPerMOutputTokens: 4.4,
    costPerMInputCached: 0.26,
    canReason: false,
    supportsAttachments: false,
    supportsStreaming: true,
    tier: 'flagship',
  },
  {
    id: 'opencodego.glm-5.1',
    name: 'GLM-5.1 (Go)',
    provider: 'opencodego',
    apiModelId: 'glm-5.1',
    contextWindow: 200_000,
    maxOutputTokens: 32_000,
    costPerMInputTokens: 1.4,
    costPerMOutputTokens: 4.4,
    costPerMInputCached: 0.26,
    canReason: false,
    supportsAttachments: false,
    supportsStreaming: true,
    tier: 'flagship',
  },
  {
    id: 'opencodego.kimi-k2.7-code',
    name: 'Kimi K2.7 Code (Go)',
    provider: 'opencodego',
    apiModelId: 'kimi-k2.7-code',
    contextWindow: 200_000,
    maxOutputTokens: 32_000,
    costPerMInputTokens: 0.95,
    costPerMOutputTokens: 4.0,
    costPerMInputCached: 0.19,
    canReason: false,
    supportsAttachments: false,
    supportsStreaming: true,
    tier: 'flagship',
  },
  {
    id: 'opencodego.kimi-k2.6',
    name: 'Kimi K2.6 (Go)',
    provider: 'opencodego',
    apiModelId: 'kimi-k2.6',
    contextWindow: 200_000,
    maxOutputTokens: 32_000,
    costPerMInputTokens: 0.95,
    costPerMOutputTokens: 4.0,
    costPerMInputCached: 0.16,
    canReason: false,
    supportsAttachments: false,
    supportsStreaming: true,
    tier: 'flagship',
  },
  {
    id: 'opencodego.deepseek-v4-pro',
    name: 'DeepSeek V4 Pro (Go)',
    provider: 'opencodego',
    apiModelId: 'deepseek-v4-pro',
    contextWindow: 200_000,
    maxOutputTokens: 32_000,
    costPerMInputTokens: 1.74,
    costPerMOutputTokens: 3.48,
    costPerMInputCached: 0.0145,
    canReason: false,
    supportsAttachments: false,
    supportsStreaming: true,
    tier: 'flagship',
  },
  {
    id: 'opencodego.deepseek-v4-flash',
    name: 'DeepSeek V4 Flash (Go)',
    provider: 'opencodego',
    apiModelId: 'deepseek-v4-flash',
    contextWindow: 200_000,
    maxOutputTokens: 32_000,
    costPerMInputTokens: 0.14,
    costPerMOutputTokens: 0.28,
    costPerMInputCached: 0.0028,
    canReason: false,
    supportsAttachments: false,
    supportsStreaming: true,
    tier: 'cheap',
  },
  {
    id: 'opencodego.mimo-v2.5',
    name: 'MiMo V2.5 (Go)',
    provider: 'opencodego',
    apiModelId: 'mimo-v2.5',
    contextWindow: 200_000,
    maxOutputTokens: 32_000,
    costPerMInputTokens: 0.14,
    costPerMOutputTokens: 0.28,
    costPerMInputCached: 0.0028,
    canReason: false,
    supportsAttachments: false,
    supportsStreaming: true,
    tier: 'cheap',
  },
  {
    id: 'opencodego.mimo-v2.5-pro',
    name: 'MiMo V2.5 Pro (Go)',
    provider: 'opencodego',
    apiModelId: 'mimo-v2.5-pro',
    contextWindow: 200_000,
    maxOutputTokens: 32_000,
    costPerMInputTokens: 1.74,
    costPerMOutputTokens: 3.48,
    costPerMInputCached: 0.0145,
    canReason: false,
    supportsAttachments: false,
    supportsStreaming: true,
    tier: 'flagship',
  },

  // ── Anthropic-compatible models (/v1/messages) ───────────────────────────
  {
    id: 'opencodego.minimax-m3',
    name: 'MiniMax M3 (Go)',
    provider: 'opencodego',
    apiModelId: 'minimax-m3',
    contextWindow: 200_000,
    maxOutputTokens: 32_000,
    costPerMInputTokens: 0.3,
    costPerMOutputTokens: 1.2,
    costPerMInputCached: 0.06,
    canReason: false,
    supportsAttachments: false,
    supportsStreaming: true,
    tier: 'flagship',
  },
  {
    id: 'opencodego.minimax-m2.7',
    name: 'MiniMax M2.7 (Go)',
    provider: 'opencodego',
    apiModelId: 'minimax-m2.7',
    contextWindow: 200_000,
    maxOutputTokens: 32_000,
    costPerMInputTokens: 0.3,
    costPerMOutputTokens: 1.2,
    costPerMInputCached: 0.06,
    canReason: false,
    supportsAttachments: false,
    supportsStreaming: true,
    tier: 'flagship',
  },
  {
    id: 'opencodego.minimax-m2.5',
    name: 'MiniMax M2.5 (Go)',
    provider: 'opencodego',
    apiModelId: 'minimax-m2.5',
    contextWindow: 200_000,
    maxOutputTokens: 32_000,
    costPerMInputTokens: 0.3,
    costPerMOutputTokens: 1.2,
    costPerMInputCached: 0.06,
    canReason: false,
    supportsAttachments: false,
    supportsStreaming: true,
    tier: 'flagship',
  },
  {
    id: 'opencodego.qwen3.7-max',
    name: 'Qwen3.7 Max (Go)',
    provider: 'opencodego',
    apiModelId: 'qwen3.7-max',
    contextWindow: 200_000,
    maxOutputTokens: 32_000,
    costPerMInputTokens: 2.5,
    costPerMOutputTokens: 7.5,
    costPerMInputCached: 0.5,
    canReason: false,
    supportsAttachments: false,
    supportsStreaming: true,
    tier: 'flagship',
  },
  {
    id: 'opencodego.qwen3.7-plus',
    name: 'Qwen3.7 Plus (Go)',
    provider: 'opencodego',
    apiModelId: 'qwen3.7-plus',
    contextWindow: 256_000,
    maxOutputTokens: 32_000,
    costPerMInputTokens: 0.4,
    costPerMOutputTokens: 1.6,
    costPerMInputCached: 0.04,
    canReason: false,
    supportsAttachments: false,
    supportsStreaming: true,
    tier: 'fast',
  },
  {
    id: 'opencodego.qwen3.6-plus',
    name: 'Qwen3.6 Plus (Go)',
    provider: 'opencodego',
    apiModelId: 'qwen3.6-plus',
    contextWindow: 256_000,
    maxOutputTokens: 32_000,
    costPerMInputTokens: 0.5,
    costPerMOutputTokens: 3.0,
    costPerMInputCached: 0.05,
    canReason: false,
    supportsAttachments: false,
    supportsStreaming: true,
    tier: 'fast',
  },
];
